version: 1.0.{build}-{branch}

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails
  
services:
  - mongodb

before_build:
  #wait a few seconds before invoking mongo operations to give time for MongoDB to initialize
  - ping -n 30 127.0.0.1 > nul
  - c:\mongodb\bin\mongo --version
  #import test json data
  - c:\mongodb\bin\mongo testdb --eval 'db.createUser( { "user":"build",pwd:"test","roles":[{"role":"readWrite","db":"testdb"}]});'  
  - c:\mongodb\bin\mongo testdb c:\projects\opengrid-svc-template\src\test\resources\testdata.js
  
build_script:
  - mvn install -f .\opengridservice\pom.xml

# to disable deployment
deploy: off

notifications:
  # Email
  - provider: Email
    to:
      - rladines@eki-consulting.com
    on_build_status_changed: true  
